FROM golang

ADD . /go/src/github.com/klekih/cityactor

RUN go get -u github.com/klekih/city/common

RUN go install github.com/klekih/cityactor

WORKDIR /go/src/github.com/klekih/cityactor

ENTRYPOINT /go/bin/cityactor

