FROM golang

ADD . /go/src/github.com/tomagb/cityactor

RUN go get -u github.com/tomagb/city/common

RUN go install github.com/tomagb/cityactor

WORKDIR /go/src/github.com/tomagb/cityactor

ENTRYPOINT /go/bin/cityactor

